In [21]:
import pandas as pd
%matplotlib inline

In [6]:
traindf = pd.read_csv('assets/train.csv')
testdf = pd.read_csv('assets/test.csv')

In [25]:
traindf

        Store  Dept        Date  Weekly_Sales IsHoliday
0           1     1  2010-02-05      24924.50     False
1           1     1  2010-02-12      46039.49      True
2           1     1  2010-02-19      41595.55     False
3           1     1  2010-02-26      19403.54     False
4           1     1  2010-03-05      21827.90     False
5           1     1  2010-03-12      21043.39     False
6           1     1  2010-03-19      22136.64     False
7           1     1  2010-03-26      26229.21     False
8           1     1  2010-04-02      57258.43     False
9           1     1  2010-04-09      42960.91     False
10          1     1  2010-04-16      17596.96     False
11          1     1  2010-04-23      16145.35     False
12          1     1  2010-04-30      16555.11     False
13          1     1  2010-05-07      17413.94     False
14          1     1  2010-05-14      18926.74     False
15          1     1  2010-05-21      14773.04     False
16          1     1  2010-05-28      15580.43     False
17          1     1  2010-06-04      17558.09     False
18          1     1  2010-06-11      16637.62     False
19          1     1  2010-06-18      16216.27     False
20          1     1  2010-06-25      16328.72     False
21          1     1  2010-07-02      16333.14     False
22          1     1  2010-07-09      17688.76     False
23          1     1  2010-07-16      17150.84     False
24          1     1  2010-07-23      15360.45     False
25          1     1  2010-07-30      15381.82     False
26          1     1  2010-08-06      17508.41     False
27          1     1  2010-08-13      15536.40     False
28          1     1  2010-08-20      15740.13     False
29          1     1  2010-08-27      15793.87     False
...       ...   ...         ...           ...       ...
421540     45    98  2012-04-06        778.70     False
421541     45    98  2012-04-13        559.14     False
421542     45    98  2012-04-20        605.80     False
421543     45    98  2012-04-27        619.41     False
421544     45    98  2012-05-04        694.25     False
421545     45    98  2012-05-11        893.60     False
421546     45    98  2012-05-18        745.44     False
421547     45    98  2012-05-25        795.94     False
421548     45    98  2012-06-01        874.64     False
421549     45    98  2012-06-08        713.50     False
421550     45    98  2012-06-15        856.35     False
421551     45    98  2012-06-22        622.62     False
421552     45    98  2012-06-29        690.52     False
421553     45    98  2012-07-06        659.65     False
421554     45    98  2012-07-13        695.21     False
421555     45    98  2012-07-20        845.30     False
421556     45    98  2012-07-27        657.63     False
421557     45    98  2012-08-03        516.46     False
421558     45    98  2012-08-10        727.49     False
421559     45    98  2012-08-17        500.16     False
421560     45    98  2012-08-24        415.40     False
421561     45    98  2012-08-31        346.04     False
421562     45    98  2012-09-07        352.44      True
421563     45    98  2012-09-14        605.96     False
421564     45    98  2012-09-21        467.30     False
421565     45    98  2012-09-28        508.37     False
421566     45    98  2012-10-05        628.10     False
421567     45    98  2012-10-12       1061.02     False
421568     45    98  2012-10-19        760.01     False
421569     45    98  2012-10-26       1076.80     False

[421570 rows x 5 columns]